"""
Four Pillars v3.9.0 signal pipeline.

Changes from four_pillars_v386.py:
- Uses state_machine_v390 (Grade C removed from state machine)
- require_stage2 removed (not in Pine v3.8.2 source)
- rot_level removed (not in Pine v3.8.2 source)
- BBW wired in: calculate_bbwp() called after compute_clouds()
  Adds 10 bbwp_ columns to df so engine/dashboard can snapshot volatility at entry
- cloud3_allows_long / cloud3_allows_short columns added to output df
  Engine uses these for directional gate decisions
- long_c / short_c columns still emitted (all zeros) for schema compatibility
  with existing dashboard code — engine ignores them and assigns C label itself

Source of truth: four_pillars_v3_8_2_strategy.pine
"""

import numpy as np
import pandas as pd

from .stochastics import compute_all_stochastics
from .clouds import compute_clouds
from .bbwp import calculate_bbwp
from .state_machine_v390 import FourPillarsStateMachine390


def compute_signals(df: pd.DataFrame, params: dict = None) -> pd.DataFrame:
    """
    Run the full Four Pillars v3.9.0 signal pipeline on OHLCV data.

    Args:
        df: DataFrame with columns [timestamp, open, high, low, close, base_vol, quote_vol]
        params: Strategy parameters. See defaults below.

    Returns:
        DataFrame with all indicator and signal columns added.
        New columns vs v386:
          - bbwp_value, bbwp_ma, bbwp_bbw_raw, bbwp_spectrum,
            bbwp_state, bbwp_points, bbwp_is_blue_bar, bbwp_is_red_bar,
            bbwp_ma_cross_up, bbwp_ma_cross_down
          - cloud3_allows_long, cloud3_allows_short (bool)
        Removed columns vs v386:
          - long_c, short_c are zeroed (not generated by state machine)
    """
    if params is None:
        params = {}

    # Step 1: stochastic indicators
    df = compute_all_stochastics(df, params)

    # Step 2: Ripster EMA clouds + price position columns
    df = compute_clouds(df, params)

    # Step 3: BBW volatility context (now wired in — was orphaned in v386)
    try:
        df = calculate_bbwp(df, params)
    except Exception as e:
        # Non-fatal: if BBW fails (e.g. missing close col variant), continue without it
        import warnings
        warnings.warn(f"BBW calculation failed, skipping: {e}", stacklevel=2)

    # Step 4: ATR — Wilder's RMA matching Pine ta.atr(14)
    atr_len = params.get("atr_length", 14)
    tr = np.maximum(
        df["high"].values - df["low"].values,
        np.maximum(
            np.abs(df["high"].values - np.roll(df["close"].values, 1)),
            np.abs(df["low"].values  - np.roll(df["close"].values, 1))
        )
    )
    tr[0] = df["high"].iloc[0] - df["low"].iloc[0]
    atr = np.full(len(tr), np.nan)
    atr[atr_len - 1] = np.mean(tr[:atr_len])
    for i in range(atr_len, len(tr)):
        atr[i] = (atr[i - 1] * (atr_len - 1) + tr[i]) / atr_len
    df["atr"] = atr

    # Step 5: cloud3_allows_long / cloud3_allows_short
    # price_pos: 1=above cloud3, 0=inside, -1=below (set by compute_clouds)
    if "price_pos" in df.columns:
        df["cloud3_allows_long"]  = df["price_pos"] >= 0
        df["cloud3_allows_short"] = df["price_pos"] <= 0
    else:
        df["cloud3_allows_long"]  = True
        df["cloud3_allows_short"] = True

    # Step 6: Bar-by-bar state machine — produces A and B only
    sm = FourPillarsStateMachine390(
        cross_level     = params.get("cross_level",     25),
        zone_level      = params.get("zone_level",      30),
        stage_lookback  = params.get("stage_lookback",  10),
        allow_b         = params.get("allow_b_trades",  True),
        b_open_fresh    = params.get("b_open_fresh",    True),
        cloud2_reentry  = params.get("cloud2_reentry",  True),
        reentry_lookback= params.get("reentry_lookback",10),
        use_ripster     = params.get("use_ripster",     False),
        use_60d         = params.get("use_60d",         False),
    )

    n = len(df)
    signals = {
        "long_a":        np.zeros(n, dtype=bool),
        "long_b":        np.zeros(n, dtype=bool),
        "long_c":        np.zeros(n, dtype=bool),  # always zero — engine assigns C
        "short_a":       np.zeros(n, dtype=bool),
        "short_b":       np.zeros(n, dtype=bool),
        "short_c":       np.zeros(n, dtype=bool),  # always zero
        "reentry_long":  np.zeros(n, dtype=bool),
        "reentry_short": np.zeros(n, dtype=bool),
    }

    stoch_9    = df["stoch_9"].values
    stoch_14   = df["stoch_14"].values
    stoch_40   = df["stoch_40"].values
    stoch_60   = df["stoch_60"].values
    stoch_60_d = df["stoch_60_d"].values
    price_pos  = df["price_pos"].values
    cross_above = df["price_cross_above_cloud2"].values
    cross_below = df["price_cross_below_cloud2"].values

    for i in range(n):
        if np.isnan(stoch_9[i]) or np.isnan(stoch_60[i]) or np.isnan(atr[i]):
            continue

        result = sm.process_bar(
            bar_index              = i,
            stoch_9                = stoch_9[i],
            stoch_14               = stoch_14[i],
            stoch_40               = stoch_40[i],
            stoch_60               = stoch_60[i],
            stoch_60_d             = stoch_60_d[i],
            price_pos              = int(price_pos[i]),
            price_cross_above_cloud2 = bool(cross_above[i]),
            price_cross_below_cloud2 = bool(cross_below[i]),
        )

        signals["long_a"][i]       = result.long_a
        signals["long_b"][i]       = result.long_b
        signals["short_a"][i]      = result.short_a
        signals["short_b"][i]      = result.short_b
        signals["reentry_long"][i]  = result.reentry_long
        signals["reentry_short"][i] = result.reentry_short

    for col, arr in signals.items():
        df[col] = arr

    return df
