"""
Build script: writes signals/regression_channel.py and scripts/test_regression_channel.py.
Run: python scripts/build_regression_channel.py
"""
import ast
import os
import py_compile
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SIG_OUT = ROOT / "signals" / "regression_channel.py"
TST_OUT = ROOT / "scripts" / "test_regression_channel.py"

ERRORS = []


def validate_output(path):
    """Run py_compile then ast.parse on a written .py file; return True if both pass."""
    path_str = str(path)
    try:
        py_compile.compile(path_str, doraise=True)
        print("  SYNTAX OK:  " + path_str)
    except py_compile.PyCompileError as e:
        print("  SYNTAX FAIL: " + str(e))
        return False
    try:
        source = Path(path_str).read_text(encoding="utf-8")
        ast.parse(source, filename=path_str)
        print("  AST OK:     " + path_str)
    except SyntaxError as e:
        print("  AST FAIL line " + str(e.lineno) + ": " + str(e.msg) + " in " + path_str)
        return False
    return True


def build_lines_regression_channel():
    """Return list of source lines for signals/regression_channel.py."""
    L = []
    L.append('"""')
    L.append("Regression channel module: pre-stage-1 orderly decline gate and stage-1-to-stage-2 anchored channel.")
    L.append("")
    L.append("Integration context (state machine caller, do not implement here):")
    L.append("")
    L.append("  At Stage 1 entry (stoch_9 crosses below 25 for first time):")
    L.append("    self.stage1_bar = current_bar_index")
    L.append("    pre_window = prices[current_bar - pre_lookback : current_bar + 1]")
    L.append("    self.pre_ch = fit_channel(pre_window)")
    L.append("    self.ch_gate_passed = pre_stage1_gate(self.pre_ch)")
    L.append("")
    L.append("  At Stage 2 exit (stoch_9 crosses above 25, divergence confirmed):")
    L.append("    if not self.ch_gate_passed:")
    L.append("        reject signal")
    L.append("    anchored = compute_channel_anchored(prices, self.stage1_bar, current_bar)")
    L.append("    if price_in_lower_half(current_price, anchored.center_at_last):")
    L.append("        fire entry signal")
    L.append("    else:")
    L.append("        reject signal")
    L.append('"""')
    L.append("from collections import namedtuple")
    L.append("import numpy as np")
    L.append("")
    L.append("")
    L.append("ChannelResult = namedtuple(")
    L.append('    "ChannelResult",')
    L.append('    ["slope", "slope_pct", "r_squared", "band_width_pct", "center_at_last", "std_residuals"],')
    L.append(")")
    L.append("")
    L.append("_ZERO = ChannelResult(")
    L.append("    slope=0.0,")
    L.append("    slope_pct=0.0,")
    L.append("    r_squared=0.0,")
    L.append("    band_width_pct=0.0,")
    L.append("    center_at_last=0.0,")
    L.append("    std_residuals=0.0,")
    L.append(")")
    L.append("")
    L.append("")
    L.append("def fit_channel(prices) -> ChannelResult:")
    L.append('    """Fit linear regression to prices; return ChannelResult or zero on degenerate input."""')
    L.append("    arr = np.asarray(prices, dtype=float)")
    L.append("    n = len(arr)")
    L.append("    if n < 3:")
    L.append("        return _ZERO")
    L.append("    x = np.arange(n, dtype=float)")
    L.append("    mean_x = np.mean(x)")
    L.append("    mean_y = np.mean(arr)")
    L.append("    ss_xx = np.sum((x - mean_x) ** 2)")
    L.append("    if ss_xx == 0.0:")
    L.append("        return _ZERO")
    L.append("    slope = np.sum((x - mean_x) * (arr - mean_y)) / ss_xx")
    L.append("    intercept = mean_y - slope * mean_x")
    L.append("    fitted = intercept + slope * x")
    L.append("    residuals = arr - fitted")
    L.append("    ss_res = np.sum(residuals ** 2)")
    L.append("    ss_tot = np.sum((arr - mean_y) ** 2)")
    L.append("    r_squared = 0.0 if ss_tot == 0.0 else 1.0 - ss_res / ss_tot")
    L.append("    center_at_last = intercept + slope * (n - 1)")
    L.append("    std_res = float(np.std(residuals))")
    L.append("    slope_pct = slope / mean_y if mean_y != 0.0 else 0.0")
    L.append("    band_width_pct = (2.0 * std_res / mean_y) if mean_y != 0.0 else 0.0")
    L.append("    return ChannelResult(")
    L.append("        slope=float(slope),")
    L.append("        slope_pct=float(slope_pct),")
    L.append("        r_squared=float(r_squared),")
    L.append("        band_width_pct=float(band_width_pct),")
    L.append("        center_at_last=float(center_at_last),")
    L.append("        std_residuals=float(std_res),")
    L.append("    )")
    L.append("")
    L.append("")
    L.append("def extrapolate_center(channel: ChannelResult, bars_elapsed: int) -> float:")
    L.append('    """Extend regression center forward by bars_elapsed bars past the fit window."""')
    L.append("    if bars_elapsed <= 0:")
    L.append("        return channel.center_at_last")
    L.append("    return channel.center_at_last + channel.slope * bars_elapsed")
    L.append("")
    L.append("")
    L.append("def price_in_lower_half(price: float, center: float) -> bool:")
    L.append('    """Return True if price is strictly below center (regression midline)."""')
    L.append("    return price < center")
    L.append("")
    L.append("")
    L.append("def compute_channel_anchored(all_prices, start_idx: int, end_idx: int) -> ChannelResult:")
    L.append('    """Compute regression over all_prices[start_idx:end_idx+1]; return zero if window < 3."""')
    L.append("    window = all_prices[start_idx : end_idx + 1]")
    L.append("    return fit_channel(window)")
    L.append("")
    L.append("")
    L.append("def pre_stage1_gate(channel: ChannelResult, r2_min: float = 0.45, slope_pct_max: float = -0.001) -> bool:")
    L.append('    """Return True if channel shows orderly negative slope with sufficient R-squared."""')
    L.append("    return channel.r_squared > r2_min and channel.slope_pct < slope_pct_max")
    L.append("")
    return L


def build_lines_test_regression_channel():
    """Return list of source lines for scripts/test_regression_channel.py."""
    L = []
    L.append('"""')
    L.append("Tests for regression_channel module.")
    L.append("Run: python scripts/test_regression_channel.py")
    L.append('"""')
    L.append("import sys")
    L.append("from pathlib import Path")
    L.append("import numpy as np")
    L.append("")
    L.append("ROOT = Path(__file__).resolve().parent.parent")
    L.append("sys.path.insert(0, str(ROOT))")
    L.append("")
    L.append("from signals.regression_channel import (")
    L.append("    fit_channel,")
    L.append("    extrapolate_center,")
    L.append("    price_in_lower_half,")
    L.append("    compute_channel_anchored,")
    L.append("    pre_stage1_gate,")
    L.append(")")
    L.append("")
    L.append("PASS_COUNT = 0")
    L.append("FAIL_COUNT = 0")
    L.append("")
    L.append("")
    L.append("def report(name, ok, details):")
    L.append('    """Print test name, details, and PASS/FAIL; update global counters."""')
    L.append("    global PASS_COUNT, FAIL_COUNT")
    L.append('    status = "PASS" if ok else "FAIL"')
    L.append('    print(name + " -> " + status + ("  " + details if details else ""))')
    L.append("    if ok:")
    L.append("        PASS_COUNT += 1")
    L.append("    else:")
    L.append("        FAIL_COUNT += 1")
    L.append("")
    L.append("")
    L.append("def test_orderly_decline():")
    L.append('    """Test 1: clean linear decline passes the pre-stage-1 gate."""')
    L.append("    rng = np.random.default_rng(42)")
    L.append("    prices = np.linspace(100.0, 94.0, 30) + rng.normal(0, 0.05, 30)")
    L.append("    ch = fit_channel(prices)")
    L.append("    gate = pre_stage1_gate(ch)")
    L.append('    details = "r2=" + str(round(ch.r_squared, 4)) + " slope_pct=" + str(round(ch.slope_pct, 6)) + " gate=" + str(gate)')
    L.append("    ok = ch.r_squared > 0.85 and ch.slope_pct < -0.001 and gate")
    L.append('    report("Test 1: Orderly decline", ok, details)')
    L.append("")
    L.append("")
    L.append("def test_v_bottom():")
    L.append('    """Test 2: V-bottom pattern fails the pre-stage-1 gate."""')
    L.append("    prices = [100.0] * 15 + [90.0, 90.0] + [100.0, 100.0]")
    L.append("    ch = fit_channel(prices)")
    L.append("    gate = pre_stage1_gate(ch)")
    L.append('    details = "r2=" + str(round(ch.r_squared, 4)) + " gate=" + str(gate)')
    L.append("    ok = ch.r_squared < 0.25 and not gate")
    L.append('    report("Test 2: V-bottom", ok, details)')
    L.append("")
    L.append("")
    L.append("def test_sideways_chop():")
    L.append('    """Test 3: sideways sin oscillation fails the pre-stage-1 gate."""')
    L.append("    x = np.arange(30)")
    L.append("    prices = 100.0 + 0.5 * np.sin(x)")
    L.append("    ch = fit_channel(prices)")
    L.append("    gate = pre_stage1_gate(ch)")
    L.append('    details = "slope_pct=" + str(round(ch.slope_pct, 6)) + " r2=" + str(round(ch.r_squared, 4)) + " gate=" + str(gate)')
    L.append("    ok = abs(ch.slope_pct) < 0.0005 and ch.r_squared < 0.2 and not gate")
    L.append('    report("Test 3: Sideways chop", ok, details)')
    L.append("")
    L.append("")
    L.append("def test_anchored_lower_half_accept():")
    L.append('    """Test 4: price at Stage 2 trough is in lower half of anchored channel -- ACCEPT."""')
    L.append("    seg_a = np.linspace(100.0, 96.0, 5)")
    L.append("    seg_b = np.linspace(96.0, 99.0, 5)")
    L.append("    seg_c = np.linspace(99.0, 93.0, 5)")
    L.append("    prices = list(seg_a) + list(seg_b) + list(seg_c)")
    L.append("    ch = compute_channel_anchored(prices, 0, 14)")
    L.append("    current_price = 93.0")
    L.append("    result = price_in_lower_half(current_price, ch.center_at_last)")
    L.append('    details = "center=" + str(round(ch.center_at_last, 4)) + " price=" + str(current_price) + " result=" + str(result)')
    L.append("    ok = result is True")
    L.append('    report("Test 4: Anchored lower half ACCEPT", ok, details)')
    L.append("")
    L.append("")
    L.append("def test_anchored_upper_half_reject():")
    L.append('    """Test 5: price in upper half of anchored channel returns REJECT."""')
    L.append("    seg_a = np.linspace(100.0, 96.0, 5)")
    L.append("    seg_b = np.linspace(96.0, 99.0, 5)")
    L.append("    seg_c = np.linspace(99.0, 93.0, 5)")
    L.append("    seg_d = np.linspace(93.0, 98.0, 5)")
    L.append("    prices = list(seg_a) + list(seg_b) + list(seg_c) + list(seg_d)")
    L.append("    ch = compute_channel_anchored(prices, 0, 19)")
    L.append("    current_price = 98.0")
    L.append("    result = price_in_lower_half(current_price, ch.center_at_last)")
    L.append('    details = "center=" + str(round(ch.center_at_last, 4)) + " price=" + str(current_price) + " result=" + str(result)')
    L.append("    ok = result is False")
    L.append('    report("Test 5: Anchored upper half REJECT", ok, details)')
    L.append("")
    L.append("")
    L.append("def test_extrapolate_center():")
    L.append('    """Test 6: extrapolating a declining channel extends slope downward."""')
    L.append("    prices = np.linspace(100.0, 95.0, 20)")
    L.append("    ch = fit_channel(prices)")
    L.append("    extrapolated = extrapolate_center(ch, 5)")
    L.append("    expected = ch.center_at_last + ch.slope * 5")
    L.append("    ok = extrapolated < ch.center_at_last and abs(extrapolated - expected) < 1e-9")
    L.append('    details = "center_at_last=" + str(round(ch.center_at_last, 6)) + " extrapolated=" + str(round(extrapolated, 6))')
    L.append('    report("Test 6: extrapolate_center", ok, details)')
    L.append("")
    L.append("")
    L.append("def test_price_in_lower_half_boundary():")
    L.append('    """Test 7: strict boundary: equal to center = not lower half."""')
    L.append("    r1 = price_in_lower_half(99.9, 100.0)")
    L.append("    r2 = price_in_lower_half(100.0, 100.0)")
    L.append("    r3 = price_in_lower_half(100.1, 100.0)")
    L.append('    details = "99.9<100=" + str(r1) + " 100.0<100=" + str(r2) + " 100.1<100=" + str(r3)')
    L.append("    ok = r1 is True and r2 is False and r3 is False")
    L.append('    report("Test 7: price_in_lower_half boundary", ok, details)')
    L.append("")
    L.append("")
    L.append("def test_edge_cases_no_exceptions():")
    L.append('    """Test 8: degenerate inputs return zero result without raising exceptions."""')
    L.append("    results = []")
    L.append("    try:")
    L.append("        r0 = fit_channel([])")
    L.append('        results.append("empty r2=" + str(r0.r_squared))')
    L.append("        r1 = fit_channel([100.0])")
    L.append('        results.append("len1 r2=" + str(r1.r_squared))')
    L.append("        r2 = fit_channel([100.0, 100.0])")
    L.append('        results.append("len2 r2=" + str(r2.r_squared))')
    L.append("        r3 = fit_channel([100.0, 100.0, 100.0])")
    L.append('        results.append("flat r2=" + str(r3.r_squared))')
    L.append("        r4 = compute_channel_anchored(list(range(100)), 5, 6)")
    L.append('        results.append("2bar r2=" + str(r4.r_squared))')
    L.append("        ok = True")
    L.append("    except Exception as e:")
    L.append('        results.append("EXCEPTION: " + str(e))')
    L.append("        ok = False")
    L.append('    report("Test 8: Edge cases no exceptions", ok, " | ".join(results))')
    L.append("")
    L.append("")
    L.append("def test_pre_lookback_sensitivity():")
    L.append('    """Test 9: gate is stable across 10, 20, 30 bar windows of the same orderly decline."""')
    L.append("    rng = np.random.default_rng(42)")
    L.append("    prices = np.linspace(100.0, 94.0, 30) + rng.normal(0, 0.05, 30)")
    L.append("    results = []")
    L.append("    all_pass = True")
    L.append("    for n in [10, 20, 30]:")
    L.append("        window = prices[-n:]")
    L.append("        ch = fit_channel(window)")
    L.append("        gate = pre_stage1_gate(ch)")
    L.append('        results.append("n=" + str(n) + " r2=" + str(round(ch.r_squared, 4)) + " slope_pct=" + str(round(ch.slope_pct, 6)) + " gate=" + str(gate))')
    L.append("        if not gate:")
    L.append("            all_pass = False")
    L.append('    report("Test 9: pre_lookback sensitivity", all_pass, " | ".join(results))')
    L.append("")
    L.append("")
    L.append('if __name__ == "__main__":')
    L.append("    test_orderly_decline()")
    L.append("    test_v_bottom()")
    L.append("    test_sideways_chop()")
    L.append("    test_anchored_lower_half_accept()")
    L.append("    test_anchored_upper_half_reject()")
    L.append("    test_extrapolate_center()")
    L.append("    test_price_in_lower_half_boundary()")
    L.append("    test_edge_cases_no_exceptions()")
    L.append("    test_pre_lookback_sensitivity()")
    L.append('    print("")')
    L.append('    print("Results: " + str(PASS_COUNT) + " passed, " + str(FAIL_COUNT) + " failed")')
    L.append("    if FAIL_COUNT > 0:")
    L.append("        sys.exit(1)")
    L.append("")
    return L


def write_file(path, lines):
    """Write lines to path as UTF-8; return True on success."""
    content = "\n".join(lines)
    path.write_text(content, encoding="utf-8")
    return True


def main():
    """Check existence, write files, validate each with py_compile + ast.parse."""
    files = [
        (SIG_OUT, build_lines_regression_channel),
        (TST_OUT, build_lines_test_regression_channel),
    ]

    for path, builder in files:
        print("")
        print("--- " + str(path))
        if path.exists():
            print("  WARNING: file already exists, aborting write for this file.")
            ERRORS.append(str(path) + " [EXISTS]")
            continue
        lines = builder()
        write_file(path, lines)
        print("  WRITTEN:    " + str(path))
        if validate_output(path):
            print("  [PASS] " + str(path))
        else:
            ERRORS.append(str(path))
            print("  [FAIL] " + str(path))

    print("")
    if ERRORS:
        print("BUILD FAILED — errors in: " + ", ".join(ERRORS))
        sys.exit(1)
    else:
        print("BUILD OK — all files compiled clean")


if __name__ == "__main__":
    main()
